# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: cimg/ruby:3.1.0-browsers
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          PGUSER: postgres
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: alkemy_challenge_production
          POSTGRES_PASSWORD: ""
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    steps:
      - browser-tools/install-firefox
      - browser-tools/install-geckodriver
      - checkout

      - run:
          name: Check Firefox and geckodriver is installed
          command: |
            firefox --version
            geckodriver --version

      - run: sudo gem uninstall bundler
      - run: sudo gem install bundler -v 2.0.2

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: cp .circleci/application.yml config/application.yml
      - run: cp .circleci/database.yml config/database.yml
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      # run static code analysis
      - run: bundle exec rake code_analysis

      # run tests!
      - run: bundle exec rspec --color --require spec_helper spec --format progress

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
      - store_artifacts:
          path: coverage
